# Generated by Django 4.0.4 on 2022-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('conv_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('conv_numero', models.CharField(max_length=50, verbose_name='Numero del convenio')),
                ('conv_organizacion', models.CharField(max_length=200, verbose_name='Organizacion')),
                ('conv_objeto', models.TextField(max_length=800, verbose_name='objeto')),
                ('conv_supervisor', models.CharField(max_length=200, verbose_name='Supervisor')),
                ('conv_email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('enti_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('enti_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('nive_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('nive_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Nivel',
                'managed': True,
            },
        ),
    ]
