# Generated by Django 4.0.4 on 2022-05-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='conv_telefono',
            field=models.IntegerField(default=0, verbose_name='Telefono'),
        ),
    ]
